import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Buscador from "@/components/Buscador";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "PizzaStore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
      
          {children}
        <Header />
      </body>
    </html>
  );
}
